// apps/kovapumps/components/Product.tsx
import Image from "next/image";
import Link from "next/link";

export default function Product({ product, category }) {
  return (
    <Link
      href={`/${category.slug}/${product.slug}`}
    >
      <a
        className="group relative bg-white border border-gray-200 rounded-lg flex flex-col overflow-hidden"
      >
        <div className="bg-gray-200 group-hover:opacity-75 sm:aspect-none aspect-square flex">
          {product.images.map(image => (
            <Image
              key={image.id}
              src={image.url}
              alt={image.altText}
              width={512}
              height={image.height / (image.width / 512)}
              objectFit="contain"
              className="sm:w-full sm:h-full"
            />
          ))}
        </div>
        <div className="flex-1 p-4 space-y-2 flex flex-col">
          <h3 className="text-sm font-medium text-gray-900">
            <a href={product.href}>
              <span aria-hidden="true" className="absolute inset-0" />
              {product.name}
            </a>
          </h3>
          <p className="text-sm text-gray-500">{product.description}</p>
          <div className="flex-1 flex flex-col justify-end">
            <p className="text-sm italic text-gray-500">{product.options}</p>
            <p className="text-base font-medium text-gray-900">{product.price}</p>
          </div>
        </div>
      </a>
    </Link>
  )
}

// src/lib/Product.svelte
<script>
  export let product = {};
</script>

<div class="p-4 sm:w-1/2 md:w-1/3 lg:w-1/4 sm:mb-0 mb-6">
  <div class="rounded-lg h-64 overflow-hidden">
    <img alt="content" class="object-contain object-center h-full w-full" src={product.image} />
  </div>
  <h2 class="text-xl font-medium title-font text-gray-900 mt-5">{product.name}</h2>
  <p class="text-base leading-relaxed mt-2">{product.description}</p>
  {#if product.link}
  <a href={product.link} class="text-blue-500 inline-flex items-center mt-3"
    >Learn More
    <svg
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
      class="w-4 h-4 ml-2"
      viewBox="0 0 24 24"
    >
      <path d="M5 12h14M12 5l7 7-7 7" />
    </svg>
  </a>
  {/if}
</div>
